blank_issues_enabled: false

contact_links:
  - name: Start a discussion
    url: /symless/synergy-core/discussions/new/choose

  - name: Contact tech support
    url: https://symless.com/synergy/contact
